#!/bin/sh
#
# fsprotect
#

# Change to yes for debug messages
DEBUG=no

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
	# get pre-requisites
	prereqs)
		prereqs
		exit 0
	;;
esac

. scripts/functions

#set -x 

#
# Echo a command and then run it
#
run_echo()
{
	if [ "$DEBUG" = "yes" ] ; then
		_log_msg "$* \n"
	fi

	if ! $* ; then
		panic "Failed!"
		exit 1
	fi
}

# Check if we want fsprotect
want_fsprotect()
{
	[ -e /proc/cmdline ] || return 1
#	grep "\<single\>" /proc/cmdline > /dev/null 2>&1 && return 1
	grep "\<nofsprotect\>" /proc/cmdline > /dev/null 2>&1 && return 2
	grep "\<fsprotect\>" /proc/cmdline > /dev/null 2>&1 && return 0

	return 1
}

# Check if overlay is supported
has_overlay()
{
	[ -e /proc/filesystems ] || return 1

	grep "\<overlay\>" /proc/filesystems > /dev/null 2>&1 && return 0

	return 1
}

want_fsprotect
T=$?
if ! [ "$T" = 0 ] ; then
	if [ "$T" = 2 ] ; then
		log_warning_msg "fsprotect: We don't want fsprotect"
	fi
	exit 0
fi

if ! [ -x /bin/is_overlayfs ] ; then
	log_failure_msg "is_overlayfs not found !"
	exit 1
fi

if is_overlayfs / ; then
	log_warning_msg "fsprotect: Already started"
	exit 0
fi

# Load the module
modprobe overlay > /dev/null 2>&1 || true

if ! has_overlay ; then
	log_failure_msg "fsprotect: No overlay kernel support !"
	exit 1
fi

# Determine tmpfs size or fallback to 512MB
SZ=512M
for x in `cat /proc/cmdline` ; do
	case "$x" in 
		fsprotect=*)
			# According to bug #564141 this is supported
			# by dash (tested - works)
			SZ="${x#fsprotect=}"

			# Avoid bashism for initramfs
			# SZ=`echo "$x" | sed -e 's/^fsprotect=//'`

			# If size is "auto" then use half memory size
			# which is tmpfs' default value
			if [ "x$SZ" = "xauto" ] ; then
				SZ='50%'
			fi
			;;
	esac
done

BASE=/fsprotect

log_begin_msg "Setting up fsprotect (overlay):"
[ "$DEBUG" = "yes" ] &&  _log_msg "#######################################################"
[ -d $BASE ] || ( mkdir -m 700 $BASE || mkdir $BASE )
[ -d $BASE/system ] || mkdir $BASE/system
[ -d $BASE/tmp ] || mkdir $BASE/tmp
[ -d $BASE/overlay ] || mkdir $BASE/overlay
[ "$DEBUG" = "yes" ] && _log_msg "#######################################################"

# What we do:
# -----------
# Bind the root filesystem to /fsprotect/system
# Mount a tmpfs to /fsprotect/tmp
# Create an overlay of /fsprotect/system and /fsprotect/tmp
# Umount old root
# Bind our overlay to the ${rootmnt}
# Umount our overlay
# Move /fsprotect/system and /fsprotect/tmp inside the overlay
run_echo "mount -n -o bind ${rootmnt} $BASE/system"	# Mount the root filesystem
run_echo "mount -n -t tmpfs -o mode=755,size=$SZ none $BASE/tmp"	# Mount the tmpfs
[ -d $BASE/tmp/upper ] || mkdir $BASE/tmp/upper
[ -d $BASE/tmp/work ] || mkdir $BASE/tmp/work
run_echo "mount -n -t overlay -o upperdir=$BASE/tmp/upper,lowerdir=$BASE/system,workdir=$BASE/tmp/work overlay $BASE/overlay"	# Make the overlayfs
run_echo "umount ${rootmnt}"			# Umount old root
run_echo "mount -n -o move $BASE/overlay ${rootmnt}"	# Use the overlay as the new root
run_echo "mkdir ${rootmnt}$BASE"	# Create the in-new-root directories
run_echo "mkdir ${rootmnt}$BASE/system"
run_echo "mkdir ${rootmnt}$BASE/tmp"
run_echo "mount -n -o move $BASE/system ${rootmnt}$BASE/system"	# Move those dirs inside the new root
run_echo "mount -n -o move $BASE/tmp ${rootmnt}$BASE/tmp"

# This one will prevent FSCKs
touch ${rootmnt}/fastboot

# [ "$DEBUG" = "yes" ] && _log_msg "#######################################################"
# [ "$DEBUG" = "yes" ] && /sbin/aufsctl ${rootmnt} --list
# [ "$DEBUG" = "yes" ] && _log_msg "#######################################################"
log_end_msg "Done..."
[ "$DEBUG" = "yes" ] && sleep 3
exit 0

