#!/bin/sh

PREREQ=""
prereqs()
{
	echo "$PREREQ"
}

case $1 in
	prereqs)
		prereqs
		exit 0
	;;
esac

. /usr/share/initramfs-tools/hook-functions

manual_add_modules overlay
# force_load overlay

copy_exec /bin/grep "/bin"
copy_exec /bin/touch "/bin"
copy_exec /bin/is_overlayfs "/bin"

