#!/bin/sh

PREREQ=""
prereqs()
{
	echo "$PREREQ"
}

case $1 in
	prereqs)
		prereqs
		exit 0
	;;
esac

. /usr/share/initramfs-tools/hook-functions

manual_add_modules aufs
# force_load aufs

copy_exec /bin/grep "/bin"
copy_exec /sbin/is_aufs "/bin"

