#!/bin/sh
# postinst script for fsprotect
#
# see: dh_installdeb(1)

set -e

case "$1" in
    configure|reconfigure)
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

[ -x /usr/sbin/update-initramfs ] && /usr/sbin/update-initramfs -u > /dev/null

#DEBHELPER#

exit 0


